display_errors = On
max_execution_time = 60
max_input_time = 60
max_input_vars = 1000
memory_limit = 512M
post_max_size = 516M
session.save_handler = files
;session.save_path ="/var/cpanel/php/sessions/ea-php82"
session.use_strict_mode = 0
session.use_cookies = 1
session.use_only_cookies = 1
session.name = KENSHYDOKAN_SESSID
session.auto_start = 0
session.cookie_lifetime = 0
session.cookie_path = /
session.serialize_handler = php
session.gc_probability = 1
session.gc_divisor = 1000
session.gc_maxlifetime = 1440
session.referer_check =
session.cache_limiter = nocache
session.cache_expire = 180
session.use_trans_sid = 0
session.sid_length = 26
session.trans_sid_tags = "a=href,area=href,frame=src,form="
session.sid_bits_per_character = 5
upload_max_filesize = 512M
zlib.output_compression = Off